### PR TITLE
Use prefill for term consistency 

### PR DESCRIPTION
**Pull request by jinhongyii**
This PR update the term name: encoding->prefill so that it is consistent with mlc-llm

### CODE REVIEW

**Review by tqchen — APPROVED** [review]

**Review by tqchen — APPROVED** [review]

**Review by tqchen — APPROVED** [review]

**Comment by tqchen** [comment]
still need to update wasm

**Comment by DustinBrett** [comment]
Thanks for all these improvements! Would it be possible to get another run of GitHub Actions for those of us that are unable to build this project but want to be able to work with the latest iterations?

**Comment by tqchen** [comment]
yap, i believe @jinhongyii @MasterJH5574  will release something soon

**Comment by jinhongyii** [comment]
We alreday run Github Actions and you can see the latest updates on our demo

**Pull request merged**
