### PR TITLE
New Chatbox Design for simple-chat

### PR DESCRIPTION
**Pull request by tlopex**
I would like to submit a pr in which I have designed a new chatbox for simple chats.
Attached is an image illustrating the design and layout of the new chatbox：
image

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks @tlopex , would be good to learn from styles in existing UX. Atm it is. abit too much in terms of gradient colors. 

Usually most chat ui goes for simple dark mode similar to chatgpt style for example here is one from ollama https://github.com/ollama-webui/ollama-webui

**Comment by tlopex** [comment]
This is my modified UI that complies with ChatGPT's dark mode. If this UI is acceptable, I plan to continue updating based on this version. Attached is an image illustrating the design and layout of the updated chatbox：
QQ截图20231218004843

**Comment by tqchen** [comment]
looks good

**Comment by tlopex** [comment]
I adjusted the reset button to the right side of the send button and replaced the text 'reset' with a refresh icon. Additionally, I added the MLC logo to the center of the chatbox, which will disappear when the conversation starts.
QQ截图20231218004843

**Comment by tlopex** [comment]
I moved the reset button to the right of the send button and replaced the text of the reset button with a refresh icon. Additionally, I placed the MLC logo in the center of the chat box, which will disappear when the conversation starts.
image

**Comment by tqchen** [comment]
I think we don't need logo fow now and just focus on the chat interface is fine, as it can be reused by others

**Comment by tlopex** [comment]
I removed the logo, moved the dropdown menu to the top of the chat box, and adjusted the colors to make the overall appearance consistent.

**Comment by tlopex** [comment]
I feel that the basic UI beautification work has been completed. Are there any elements that need to be added or modified?

**Comment by tqchen** [comment]
Thanks @tlopex . I will assign @CharlieFRuan for review and check

**Comment by CharlieFRuan** [comment]
@tlopex Really appreciate the work! Will review it today or early tomorrow!

**Comment by CharlieFRuan** [comment]
@tlopex Thanks for the work, the new UI looks great!

Only one nit pick, when trying to run [local_deploy_site.sh](https://github.com/mlc-ai/web-llm/blob/main/scripts/local_deploy_site.sh) (simulating what we would see in https://webllm.mlc.ai/#chat-demo), a longer model name would be chopped off. This problem is not present if we only run `simple-chat` though. Would be great if we could fix this!

image

**Comment by tlopex** [comment]
@CharlieFRuan Thanks for your reviewing!
I can't figure out why the fonts and sizes of the dropdown bars on the websites built in two different ways are different, so I just made the dropdown bar a bit wider, so that the names of the models can be displayed completely no matter how the site is opened. Btw, I also removed the font style from the dropdown bar because I found that it would cause the underscore to be dropped when setting up with Jekyll.
Modified version:
S_T0$_ %F2BT{YJBAF~8L

**Review by CharlieFRuan — APPROVED** [review]
@tlopex Thanks for the fix, LGTM!

cc @tqchen

**Local simple-chat:**
Screenshot 2023-12-24 at 2 49 07 PM

**Deployed on demo website:**
Screenshot 2023-12-24 at 2 50 29 PM

**Comment by tqchen** [comment]
Thanks everyone, @CharlieFRuan feel free to merge and followup with deployment

**Pull request merged**
