### PR TITLE
Update cleanModelUrl to support non-main branches

### PR DESCRIPTION
**Pull request by bdpoff**
This is a small change to `cleanModelUrl` to allow for more flexibility and backwards compatibility in the modelUrl. The function will now only append "resolve/main/" if the provided URL does not already contain "resolve". Tested with the following URL formats to ensure that all work.

- https://huggingface.co/USER/MODEL
- https://huggingface.co/USER/MODEL/
- https://huggingface.co/USER/MODEL/resolve/branch
- https://huggingface.co/USER/MODEL/resolve/branch/

### CODE REVIEW

**Comment by CharlieFRuan** [comment]
Thank you! I think this is a good change; could you add two things if you have a chance (otherwise I can also do it):
- Update the unit test here to include the four cases you listed https://github.com/mlc-ai/web-llm/blob/main/tests/util.test.ts#L30
  - Can be verified with `npm test` (not yet integrated to CI yet)
- Update the docstring for `ModelRecord.model` to list the four formats we expect: https://github.com/mlc-ai/web-llm/blob/main/src/config.ts#L239

Thanks!

**Comment by bdpoff** [comment]
Done and done!
```
 PASS  tests/util.test.ts
  Check getTopLogprobs correctness
    ✓ Correctness test 1 (3 ms)
    ✓ Zero top_logprobs (1 ms)
  Test clean model URL
    ✓ Input does not have branch or trailing /
    ✓ Input does not have branch but has trailing / (1 ms)
    ✓ Input has branch but does not have trailing / (1 ms)
    ✓ Input has branch and trailing/

Test Suites: 1 passed, 1 total
Tests:       6 passed, 6 total
Snapshots:   0 total
Time:        1.731 s, estimated 4 s
Ran all test suites matching /tests\/util.test.ts/i.
Done in 2.26s.
```

**Review by CharlieFRuan — APPROVED** [review]
LGTM, thanks!

**Comment by bdpoff** [comment]
Oops, sorry, just got notified that I missed a semicolon here:
https://github.com/mlc-ai/web-llm/blob/main/src/support.ts#L75
I hope that is a quick fix, sorry again, can fix it myself if that's preferred.

**Comment by CharlieFRuan** [comment]
No worries! I'll fix it in the next PR

**Pull request merged**
