### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tpoisonooo**
Add gem mirror doc for gem/web beginner like me..

### CODE REVIEW

**Comment by tpoisonooo** [comment]
@jinhongyii  Please review.

**Comment by tpoisonooo** [comment]
I have tried  `cuda` version
```bash
$ python3 -m pip install https://github.com/mlc-ai/utils/releases/download/v0.9.dev0/mlc_ai_nightly_cu116-0.12.dev665%2Bgdc912c8f2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
```

But got this error when build the model
```bash
python3 build.py --model llama-7b
Traceback (most recent call last):
  File "build.py", line 13, in <module>
    import web_llm
  File "/workspace/GitProjects/web-llm/web_llm/__init__.py", line 2, in <module>
    from . import transform
  File "/workspace/GitProjects/web-llm/web_llm/transform/__init__.py", line 1, in <module>
    from .dispatch_tir_operator import DispatchTIROperator
  File "/workspace/GitProjects/web-llm/web_llm/transform/dispatch_tir_operator.py", line 2799, in <module>
    tvm.ir.structural_hash(softmax_1xn_before): softmax_1xn_sch_func(),
  File "/workspace/GitProjects/web-llm/web_llm/transform/dispatch_tir_operator.py", line 352, in softmax_1xn_sch_func
    sch.compute_inline(b0)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/tvm/tir/schedule/_type_checker.py", line 339, in wrap
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/tvm/tir/schedule/schedule.py", line 1980, in compute_inline
    _ffi_api.ScheduleComputeInline(self, block)  # type: ignore # pylint: disable=no-member
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 262, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 251, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
tvm.tir.schedule.schedule.ScheduleError: Traceback (most recent call last):
  3: TVMFuncCall
..
Error message: The body of the inlined block should be in form of
    'A[i, j, k, ...] = f(i, j, k, ...)',
where the indices on the left are distinct atomic variables,
and there should be no variables other than the index variables

```

Can you add some doc about cuda target ?

**Comment by tpoisonooo** [comment]
cc @tqchen

**Review by jinhongyii — APPROVED** [review]
Sorry for the late approval. It looks good to me.

**Pull request merged**
