### PR TITLE
Use the npm package in the next example. Confirmed that this works locally.

### PR DESCRIPTION
**Pull request by narangkay**

### CODE REVIEW

**Review by tqchen — APPROVED** [review]

**Comment by tqchen** [comment]
When I run 
```
npm install
npm run dev
```

It shows an error 
```

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/tqchen/github/web-llm/examples/next-simple-chat/node_modules/next/dist/telemetry/post-payload.js:17:20)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```

**Comment by narangkay** [comment]
Is this when you're in the next example or in a regular one?

**Comment by narangkay** [comment]
Hmm, let me try to replicate, I'd tried it yesterday and it worked with both building from source and the prebuilt package.

**Comment by narangkay** [comment]
Huh.. just tried again and it indeed doesn't work unless you build web-llm locally. In fact, it still works if you have previously built web-llm locally and switch the dependency in package.json to the pre-built version.. I opened #140 with a bunch of details from my local runs


Unfortunately I might not have time until the weekend to look at this more closely.. for now maybe we can revert the commit that uses the prebuilt npm package in the next example?

**Pull request merged**
