### PR TITLE
Update Chrome extension to work with both WebGPU and local server

### PR DESCRIPTION
**Pull request by sudeepag**
This PR updates the Chrome extension to run in two modes:
- Using the `ChatRestModule`, which uses a local/hosted server to run the model. 
  - This requires the user to launch the server before using the Chrome extension, which interacts with the server using the REST API.
  - The `ChatRestModule` will be created in the background service worker, so it should persist between interactions.
- Using the `ChatModule`, which runs the model using WebGPU.
  - This does not require any additional user actions before using the extension.
  - The `ChatModule` cannot be created in the background service worker, so it needs to be loaded from cache every time the user interacts with the extension. This takes several seconds. 

Some additional observations / limitations:
- As far as I can tell, Chrome extensions can only [support](https://developer.chrome.com/docs/extensions/mv3/service_workers/) background service workers, which don't currently have support for WebGPU yet, as mentioned in https://github.com/gpuweb/gpuweb/issues/4197. This means that the WebGPU mode will only work from the main script and not the background worker.
- This approach does not work with Manifest v3 because of the following error:
```
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
```
I suspect it is because we are evaluating some third party code which is not in the extension. There seems to be a dependency on 'unsafe-eval' in the Content Security Policy, but according to the Chrome extension [documentation](https://developer.chrome.com/docs/extensions/mv3/manifest/content_security_policy/), this is not allowed starting v3. I managed to get it to work in Manifest v2, but Manifest v2 will be getting deprecated this year.

### CODE REVIEW

**Comment by sudeepag** [comment]
@tqchen I'm running into an issue with WebGPU in the web-llm `ChatModule` and could use some pointers if you have any ideas. Everything works fine if I use the `RestChatModule` through the REST API, but when I try to load it using WebGPU, I am running into some errors.  I'm calling reload [here](https://github.com/mlc-ai/web-llm/pull/182/files#diff-34a164d8845b5bb2b49a96acd0b6db199d2428e569db592605d826b186eb0a3fR10-R12), which should download the model into the cache. I then ran into the following error:
```
Uncaught (in promise) CompileError: WebAssembly.instantiate(): Refused to compile or instantiate WebAssembly module because neither 'wasm-eval' nor 'unsafe-eval' is an allowed source of script in the following Content Security Policy directive: "script-src 'self'"
```
I got around this by including a CSP in the extension [manifest](https://github.com/mlc-ai/web-llm/pull/182/files#diff-ca85ba3325a9400e707e9cdaa99d4a4855f458217a79ea6574551ddf508150dfR12-R14):
```
"content_security_policy": {
    "extension_pages": "script-src 'self' 'wasm-unsafe-eval'; default-src 'self'"
},
```
But then I started getting this error:
```
Uncaught (in promise) Error: Cannot find WebGPU in the environment
```
Do you have any ideas on how I can debug this further? I am testing with the latest Chrome Canary (118) with `--enable-features=AllowWasmInMV3 --enable-unsafe-webgpu` args, and the web-llm [demo](https://webllm.mlc.ai/ ) is working successfully so I suspect its some issue related to accessing the wasm from the extension, but I'm not sure how I can debug further.

**Comment by tqchen** [comment]
Seems this is still being worked on with this tracking issue https://github.com/gpuweb/gpuweb/issues/4197 so not blocked by ourside.

**Comment by tqchen** [comment]
It would be good to test out SharedWorker, and see if we can leverage that(which also persists across tabs).

**Comment by sudeepag** [comment]
> It would be good to test out SharedWorker, and see if we can leverage that(which also persists across tabs).

@tqchen Thanks, I will look into this.

**Review by tqchen — APPROVED** [review]

**Pull request merged**
