### PR TITLE
add helper methods to check cache

### PR DESCRIPTION
**Pull request by narangkay**
**NOTE**: This depends on https://github.com/mlc-ai/relax/pull/265 and cannot be merged before that PR is merged.

### CODE REVIEW

**Comment by narangkay** [comment]
fixes #148

**Comment by narangkay** [comment]
@tqchen Hi, wondering if this looks like an okay followup to https://github.com/apache/tvm/pull/15357?

**Review by tqchen — APPROVED** [review]

**Comment by tqchen** [comment]
Thanks @narangkay for pinging :) merged

**Comment by narangkay** [comment]
thank you!

**Pull request merged**
