### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gopi-suvanam**
Added dynamic import syntax for loading from CDN.

### CODE REVIEW

**Comment by CharlieFRuan** [comment]
Thanks for your contribution! Out of curiosity, I tried it out in Scribbler but ran into the following, do you know why this may be the case: 
image

**Comment by gopi-suvanam** [comment]
hi Charlie, Thanks for trying out.
Scribbler runs the notebook in a sandbox by default for web-security. This disables access to cookies/cache/local storage etc. For running WebLLM, you will have to take it out of sandbox manually by clicking the red ⤯ button at top-right corner or by clicking "Edit->Trust the NB".
Here is a working notebook on WebLLM with loading the library and running the model: https://app.scribbler.live/?jsnb=https://examples.scribbler.live/WebLLM-Experiments.jsnb

**Comment by CharlieFRuan** [comment]
Tried it out, works smoothly. Thank you so much!

**Review by CharlieFRuan — APPROVED** [review]

**Comment by gopi-suvanam** [comment]
Thanks!! Looking forward to experimenting more with WebLLM/
mlc-llm

**Pull request merged**
