### PR TITLE
Allow configuring conversation

### PR DESCRIPTION
**Pull request by DustinBrett**
I've added the ability to customize more configuration options, as well as the conversation options. I couldn't build the project as I had issues with it looking for `tvm_home`, so I have not tested this and would like some feedback on if this code makes sense.

I've created this as suggested in https://github.com/mlc-ai/web-llm/issues/115, fyi @tqchen.

### CODE REVIEW

**Review by tqchen — APPROVED** [review]

**Comment by tqchen** [comment]
@DustinBrett you can run scripts/prep_deps.sh which should create a ln for tvm hold following the build from source option. In this case the build won't be as complicated because you don't ened to build the model

**Comment by DustinBrett** [comment]
> @DustinBrett you can run scripts/prep_deps.sh which should create a ln for tvm hold following the build from source option. In this case the build won't be as complicated because you don't ened to build the model
> 
> https://github.com/mlc-ai/web-llm/blob/main/scripts/prep_deps.sh#L20

Thanks for the suggestion. Although as a Windows user I don't typically setup WSL to be able to run sh files. I'm more familiar with repos working cross platform.

**Comment by DustinBrett** [comment]
> > @DustinBrett you can run scripts/prep_deps.sh which should create a ln for tvm hold following the build from source option. In this case the build won't be as complicated because you don't ened to build the model
> > https://github.com/mlc-ai/web-llm/blob/main/scripts/prep_deps.sh#L20
> 
> Thanks for the suggestion. Although as a Windows user I don't typically setup WSL to be able to run sh files. I'm more familiar with repos working cross platform.

I'd tried to do WSL before and 20GB's of Ubuntu later I still couldn't get a build to work as it wanted CUDA cores which I couldn't do in WSL or with my AMD card. Maybe some setup instructions for Windows users who just want to contribute to the JS/TS code would help.

**Comment by tqchen** [comment]
No need to use cuda actually. The WebLLM runtime at the moment is just a runtime, and we can still leverage prebuilt wasm for tests

**Comment by tqchen** [comment]
https://github.com/mlc-ai/web-llm#build-webllm-package-from-source is the latest instruction, and then use the app-config here to get the prebuilt wasm and model https://github.com/mlc-ai/web-llm/blob/main/examples/simple-chat/src/gh-config.js  would allow us to develop TS/JS without running the model build process

**Comment by DustinBrett** [comment]
> No need to use cuda actually. The WebLLM runtime at the moment is just a runtime, and we can still leverage prebuilt wasm for tests

I can try again as it wasn't giving me any choices last time. I spent several hours in setup hell last time before I'd given up. As for running sh files, without WSL I'm not sure how to do this tbh. I don't use Linux typically as I run Windows.

**Comment by DustinBrett** [comment]
> https://github.com/mlc-ai/web-llm#build-webllm-package-from-source is the latest instruction, and then use the app-config here to get the prebuilt wasm and model https://github.com/mlc-ai/web-llm/blob/main/examples/simple-chat/src/gh-config.js would allow us to develop TS/JS without running the model build process

Do you have a platform agnostic setup as these steps won't work on Windows?

**Comment by tqchen** [comment]
Ah I see, happy to also add a prep_dep.bat for windows if that helps

Effectively it is cloning the right version of tvm to webllm/tvm_home (because we need the source to bundle tvmjs), then run the npm build on tvmjs, before running webllm build

The content of  https://github.com/mlc-ai/web-llm/blob/main/scripts/prep_deps.sh is a good ref

**Comment by DustinBrett** [comment]
> Ah I see, happy to also add a prep_dep.bat for windows if that helps
> 
> Effectively it is cloning the right version of tvm to webllm/tvm_home (because we need the source to bundle tvmjs), then run the npm build on tvmjs, before running webllm build
> 
> The content of https://github.com/mlc-ai/web-llm/blob/main/scripts/prep_deps.sh is a good ref

I can look through this sh file and try and make a bat file or manually run the equivalent commands.

**Comment by tqchen** [comment]
Likely something around (i haven't validated it)
```bash
# enable emsdk(there is a emsdk bat instruction)
# directly clone into the right location since windows symlink is flaky
git clone https://github.com/mlc-ai/relax tvm_home

cd tvm_home/web && make && npm install && npm run build && cd ../..
npm install
```

**Comment by DustinBrett** [comment]
> Likely something around (i haven't validated it)
> 
> ```shell
> # enable emsdk(there is a emsdk bat instruction)
> # directly clone into the right location since windows symlink is flaky
> git clone https://github.com/mlc-ai/relax tvm_home
> 
> cd tvm_home/web && make && npm install && npm run build && cd ../..
> npm install
> ```

`make` is not something I can run. Any ideas?

**Comment by tqchen** [comment]
OK, let me figure something out so we don't need the make step :)

**Comment by tqchen** [comment]
Try this, instead of running make,  download https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/tvmjs_runtime_wasi.js and put it into /tvm_home/web/src, then run npm install and all steps after

**Comment by DustinBrett** [comment]
> Try this, instead of running make, download https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/tvmjs_runtime_wasi.js and put it into /tvm_home/web/src, then run npm install and all steps after

Thanks for the suggestion. I've done this but running into a new issue when doing `npm run build`, it gives me this:

image

**Comment by tqchen** [comment]
we need to first run npm build in `tvm_home/web/`, which should give `tvm_home/web/lib`, the npm install in the web-llm will be able to install tvmjs

**Comment by DustinBrett** [comment]
> we need to first run npm build in `tvm_home/web/`, which should give `tvm_home/web/lib`, the npm install in the web-llm will be able to install tvmjs

Ya I'd already tried this and indeed the `lib` folder is made but it doesn't fix the fact `npm run build` can't run.

image

**Comment by tqchen** [comment]
My bad, try `npx rollup -c rollup.config.js` instead of build

**Comment by DustinBrett** [comment]
> My bad, try `npx rollup -c rollup.config.js` instead of build

Unfortunately that also didn't work.

In `web-llm`:
image

In `web-llm\tvm_home\web`:
image

**Comment by DustinBrett** [comment]
I got it to build using WSL eventually. And it built without issue. As for using the simple chat example I haven't played with it yet to see if my changes will work.

**Comment by DustinBrett** [comment]
I am unable to get the example running after everything builds. I get this error

image

**Comment by tqchen** [comment]
Merging for now to try unblock things, will make a new build around tmr. then we can figure out standalone build later. Thanks @DustinBrett

**Pull request merged**
